apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exam-mehmetonal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent-1  # Restrict to specific node
      containers:
      - name: backend
        image: alperenonal/big_data_and_ai-24_may_api:versie1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam-mehmetonal
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
