
# Frontend Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-mehmetonal
  labels:
    createdBy: "Mehmet-Alperen-Onal"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-2 
      containers:
        - image: alperenonal/big_data_and_ai-24_may_frontend:versie1
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
          env:
            - name: API_PORT
              value: "80"  # Port exposed by the API service within the cluster
            - name: API_HOST
              value: "api-service"  # Kubernetes service name for the API
            - name: NAME
              value: "Mehmet Onal"

---

# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-mehmetonal
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010















# # Frontend Deployment and Service
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   namespace: exxam-mahmoudasadiheris
#   labels:
#     createdBy: "Mahmoud-Asadi-Heris"
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: k3d-k3s-default-agent-2
#       containers:
#         - image: mahmoudasadi/big_data_and_ai-24_may_frontend:versie1
#           imagePullPolicy: Always
#           name: frontend
#           ports:
#             - containerPort: 80
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 80
#             initialDelaySeconds: 15
#             periodSeconds: 10
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   namespace: exxam-mahmoudasadiheris
# spec:
#   type: NodePort
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30000
